models:
- alias: connector_gemini_litellm
  name: connector_gemini_litellm
  provider: connectors
  purpose: connector
  endpoint: ${LITELLM_BASE_URL}
  default_params:
    connector_type: llm
    driver: litellm
    description: Gemini access via LiteLLM router
    healthcheck_path: /v1/models
  config:
    routing_model: gemini/gemini-2.5-flash
    schema:
      request:
        required:
        - model
        - messages
      response:
        required:
        - choices
    timeout_seconds: 60
    headers:
      Authorization: Bearer ${LITELLM_VIRTUAL_KEY}
- alias: connector_qwen_openai
  name: connector_qwen_openai
  provider: connectors
  purpose: connector
  endpoint: http://qwen-openai-proxy:5000
  default_params:
    connector_type: llm
    driver: openai
    description: Qwen OpenAI-compatible proxy
    healthcheck_path: /health
  config:
    routing_model: qwen3-235b-int8
    schema:
      request:
        required:
        - model
        - messages
      response:
        required:
        - choices
    timeout_seconds: 240
- alias: connector_paradedb
  name: connector_paradedb
  provider: connectors
  purpose: connector
  endpoint: postgresql://agent:agentpass@paradedb:5432/agentdb
  default_params:
    connector_type: database
    driver: postgres
    description: ParadeDB primary warehouse
    schema: public
  config:
    sslmode: prefer
- alias: connector_neo4j
  name: connector_neo4j
  provider: connectors
  purpose: connector
  endpoint: bolt://neo4j:7687
  default_params:
    connector_type: graph
    driver: neo4j
    description: Neo4j knowledge graph
    database: neo4j
  config:
    http_endpoint: http://neo4j:7474
    username: ${NEO4J_USER}
    password_env: NEO4J_PASSWORD
- alias: connector_ollama_code_embedding
  name: connector_ollama_code_embedding
  provider: connectors
  purpose: connector
  endpoint: ${CODE_EMBED_BASE_URL:-http://qwen3-embed:8080/v1/embeddings}
  default_params:
    connector_type: embedding
    driver: openai
    description: Code embedding via nomic-embed-code (llama-server)
    model: nomic-embed-code
    dims: 3584
    schema:
      request:
        required:
        - model
        - input
      response:
        required:
        - data
    timeout_seconds: 300
  config:
    api_style: openai
- alias: connector_nv_embed
  name: connector_nv_embed
  provider: connectors
  purpose: connector
  endpoint: ${NV_EMBED_BASE_URL}
  default_params:
    connector_type: embedding
    driver: openai
    description: NV-Embed-v2 embedding service
    model: nv-embed-v2
    dims: 4096
    schema:
      request:
        required:
        - model
        - input
      response:
        required:
        - data
    timeout_seconds: 120
- alias: connector_legal_embed
  name: connector_legal_embed
  provider: connectors
  purpose: connector
  endpoint: ${LEGAL_EMBED_BASE_URL}
  default_params:
    connector_type: embedding
    driver: openai
    description: Legal domain embedding service (Nomic fine-tune)
    model: legal-embed
    dims: 768
    schema:
      request:
        required:
        - model
        - input
      response:
        required:
        - data
    timeout_seconds: 120
- alias: emb-code
  name: emb-code
  provider: ollama
  purpose: embedding
  endpoint: ${CODE_EMBED_BASE_URL:-http://qwen3-embed:8080/v1/embeddings}
  dims: 3584
  default_params:
    gateway_alias: connector_ollama_code_embedding
    connector_type: embedding
    driver: ollama
    description: Active code embedding space via nomic-embed-code (llama-server)
- alias: emb-general
  name: emb-general
  provider: nvembed
  purpose: embedding
  endpoint: ${NV_EMBED_BASE_URL}
  dims: 4096
  default_params:
    model: nv-embed-v2:search_document
    path: /v1/embeddings
    timeout_seconds: 360
    description: NV-Embed-v2 general embedding space
- alias: emb-legal
  name: emb-legal
  provider: legalembed
  purpose: embedding
  endpoint: ${LEGAL_EMBED_BASE_URL}
  dims: 768
  default_params:
    model: simonosgoode/nomic_embed_fine_tune_law_1.5:search_document
    path: /v1/embeddings
    timeout_seconds: 240
    description: Nomic legal embedding space

- alias: connector_goap_planner
  name: connector_goap_planner
  provider: connectors
  purpose: connector
  endpoint: ${GOAP_PLANNER_URL}
  default_params:
    connector_type: planning
    driver: goap
    description: Goal-Oriented Action Planner service
    plan_path: /plan
    timeout_seconds: 45
